development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
    url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
  # url: redis://redistogo:0bd671ef6efef736d40d1745f545e5e1@greeneye.redistogo.com:11522/
  # :host: greeneye.redistogo.com
  # :port: 11522
  # :password: 0bd671ef6efef736d40d1745f545e5e1
  # :inline: true
  # :timeout: 1
  # channel_prefix: websock_production
