  config.web_socket_server_url = "wss://t-t-message.herokuapp.com//cable"
  config.action_cable.allowed_request_origins = [ /https?:\/\/.*/ ]
  config.action_cable.allowed_request_origins = ['https://t-t-message.herokuapp.com/', 'http://t-t-message.herokuapp.com/']
